from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timezone
from hashlib import sha256
import importlib.util
import json
from pathlib import Path
import re
import tomllib

from packaging.version import Version
import pytest


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "dependency_policy.py"
FRONTEND_LOCK = Path("/Users/zhdeng/stoa-frontend/package-lock.json")
NOW = datetime(2026, 7, 19, 9, 0, tzinfo=timezone.utc)


def _load_policy():
    spec = importlib.util.spec_from_file_location("dependency_policy", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _backend_files(tmp_path: Path, *, package: str = "demo", version: str = "1.2.3"):
    lock = tmp_path / "uv.lock"
    requirements = tmp_path / "requirements.txt"
    lock.write_text(
        f'version = 1\n[[package]]\nname = "{package}"\nversion = "{version}"\n',
        encoding="utf-8",
    )
    requirements.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv export --format requirements-txt --no-dev --no-emit-project --locked\n"
        f"{package}=={version} \\\n+    --hash=sha256:{'0' * 64}\n",
        encoding="utf-8",
    )
    return lock, requirements


def _backend_audit(*, package: str = "demo", version: str = "1.2.3", advisory: str = "GHSA-abcd-1234-wxyz"):
    return {
        "dependencies": [
            {
                "name": package,
                "version": version,
                "vulns": [
                    {
                        "id": advisory,
                        "fix_versions": ["1.2.4"],
                        "aliases": ["GHSA-alias-1234-wxyz", "CVE-2026-1000"],
                        "description": "not retained in policy output",
                    }
                ],
            }
        ],
        "fixes": [],
    }


def _ledger(*exceptions: dict[str, object]):
    return {"schema": "stoa.release.dependency-exceptions.v1", "exceptions": list(exceptions)}


def _exception(lock: Path, **overrides: object):
    value: dict[str, object] = {
        "ecosystem": "backend-python",
        "package": "demo",
        "advisory": "GHSA-abcd-1234-wxyz",
        "advisory_aliases": ["CVE-2026-1000", "GHSA-alias-1234-wxyz"],
        "installed_version": "1.2.3",
        "lock_sha256": sha256(lock.read_bytes()).hexdigest(),
        "dependency_scope": "runtime",
        "severity": "unavailable",
        "reachability": "production-reachable",
        "reachability_evidence": "runtime export and public request path review DEP-474-05-001",
        "owner": "project-owner",
        "approval_evidence": "Owner approved exact exception in conversation DEP-474-05-001",
        "expires_at": "2026-08-19T09:00:00Z",
        "target": "upgrade demo to 1.2.4",
    }
    value.update(overrides)
    return value


def _frontend_audit(*, severity: str = "high", advisory: int = 1099999, node: str = "node_modules/form-data"):
    return {
        "auditReportVersion": 2,
        "vulnerabilities": {
            "form-data": {
                "name": "form-data",
                "severity": severity,
                "isDirect": False,
                "via": [
                    {
                        "source": advisory,
                        "name": "form-data",
                        "dependency": "form-data",
                        "title": "fixture advisory",
                        "url": "https://github.com/advisories/GHSA-aaaa-bbbb-cccc",
                        "severity": severity,
                        "cwe": ["CWE-20"],
                        "cvss": {"score": 7.5, "vectorString": None},
                        "range": "<4.0.0",
                    }
                ],
                "effects": [],
                "range": "<4.0.0",
                "nodes": [node],
                "fixAvailable": True,
            }
        },
        "metadata": {
            "vulnerabilities": {"info": 0, "low": 0, "moderate": 0, "high": 1, "critical": 0, "total": 1},
            "dependencies": {"prod": 1, "dev": 0, "optional": 0, "peer": 0, "peerOptional": 0, "total": 1},
        },
    }


def test_backend_unaccepted_advisory_blocks(tmp_path):
    policy = _load_policy()
    lock, requirements = _backend_files(tmp_path)

    result = policy.evaluate_backend(
        audit=_backend_audit(),
        lock_path=lock,
        requirements_path=requirements,
        exceptions=_ledger(),
        now=NOW,
    )

    assert result["status"] == "FAIL"
    assert result["blockers"] == [
        {
            "ecosystem": "backend-python",
            "package": "demo",
            "advisory": "GHSA-abcd-1234-wxyz",
            "advisory_aliases": ["CVE-2026-1000", "GHSA-alias-1234-wxyz"],
            "installed_version": "1.2.3",
            "dependency_scope": "runtime",
            "severity": "unavailable",
            "reachability": "production-reachable",
            "fix_versions": ["1.2.4"],
        }
    ]
    assert "description" not in json.dumps(result)


def test_one_exact_unexpired_exception_matches_only_bound_advisory_version_and_lock(tmp_path):
    policy = _load_policy()
    lock, requirements = _backend_files(tmp_path)
    exact = _exception(lock)

    accepted = policy.evaluate_backend(
        audit=_backend_audit(),
        lock_path=lock,
        requirements_path=requirements,
        exceptions=_ledger(exact),
        now=NOW,
    )

    assert accepted["status"] == "PASS"
    assert accepted["blockers"] == []
    assert accepted["accepted_exceptions"] == [
        {
            "ecosystem": "backend-python",
            "package": "demo",
            "advisory": "GHSA-abcd-1234-wxyz",
            "advisory_aliases": ["CVE-2026-1000", "GHSA-alias-1234-wxyz"],
            "installed_version": "1.2.3",
            "lock_sha256": sha256(lock.read_bytes()).hexdigest(),
            "reachability": "production-reachable",
            "expires_at": "2026-08-19T09:00:00Z",
        }
    ]

    mutations = {
        "advisory": "GHSA-other-1234-wxyz",
        "advisory_aliases": ["CVE-2026-9999", "GHSA-alias-1234-wxyz"],
        "installed_version": "1.2.2",
        "lock_sha256": "f" * 64,
        "dependency_scope": "development",
        "expires_at": "2026-07-19T08:59:59Z",
    }
    for field, replacement in mutations.items():
        changed = deepcopy(exact)
        changed[field] = replacement
        with pytest.raises(policy.DependencyPolicyError):
            policy.evaluate_backend(
                audit=_backend_audit(),
                lock_path=lock,
                requirements_path=requirements,
                exceptions=_ledger(changed),
                now=NOW,
            )


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("package", "*"),
        ("advisory", "GHSA-*"),
        ("installed_version", ">=1.0"),
        ("owner", "*"),
        ("target", "later"),
        ("unexpected", "field"),
    ],
)
def test_exception_schema_rejects_wildcards_broad_targets_and_unknown_fields(tmp_path, field, value):
    policy = _load_policy()
    lock, _ = _backend_files(tmp_path)
    exception = _exception(lock)
    exception[field] = value

    with pytest.raises(policy.DependencyPolicyError):
        policy.validate_exception_ledger(_ledger(exception), now=NOW)


def test_duplicate_and_stale_unmatched_exceptions_fail_closed(tmp_path):
    policy = _load_policy()
    lock, requirements = _backend_files(tmp_path)
    exact = _exception(lock)

    with pytest.raises(policy.DependencyPolicyError, match="duplicate"):
        policy.evaluate_backend(
            audit=_backend_audit(),
            lock_path=lock,
            requirements_path=requirements,
            exceptions=_ledger(exact, deepcopy(exact)),
            now=NOW,
        )

    stale = _exception(lock, advisory="GHSA-stale-1111-2222")
    with pytest.raises(policy.DependencyPolicyError, match="unmatched"):
        policy.evaluate_backend(
            audit={"dependencies": [{"name": "demo", "version": "1.2.3", "vulns": []}], "fixes": []},
            lock_path=lock,
            requirements_path=requirements,
            exceptions=_ledger(stale),
            now=NOW,
        )


@pytest.mark.parametrize("audit_mutation", ["missing", "extra", "version"])
def test_backend_audit_must_exactly_cover_authoritative_runtime_export(tmp_path, audit_mutation):
    policy = _load_policy()
    lock, requirements = _backend_files(tmp_path)
    audit = _backend_audit()
    if audit_mutation == "missing":
        audit["dependencies"] = []
    elif audit_mutation == "extra":
        audit["dependencies"].append({"name": "other", "version": "9.9", "vulns": []})
    else:
        audit["dependencies"][0]["version"] = "9.9"

    with pytest.raises(policy.DependencyPolicyError, match="runtime export"):
        policy.evaluate_backend(
            audit=audit,
            lock_path=lock,
            requirements_path=requirements,
            exceptions=_ledger(),
            now=NOW,
        )


def test_frontend_high_and_production_medium_block_but_dev_medium_does_not():
    policy = _load_policy()

    high = policy.evaluate_frontend(
        audit=_frontend_audit(severity="high"),
        lock_path=FRONTEND_LOCK,
        exceptions=_ledger(),
        now=NOW,
    )
    medium = policy.evaluate_frontend(
        audit=_frontend_audit(severity="moderate"),
        lock_path=FRONTEND_LOCK,
        exceptions=_ledger(),
        now=NOW,
    )
    dev_medium = policy.evaluate_frontend(
        audit=_frontend_audit(severity="moderate", node="node_modules/@playwright/test"),
        lock_path=FRONTEND_LOCK,
        exceptions=_ledger(),
        now=NOW,
    )

    assert high["status"] == "FAIL"
    assert medium["status"] == "FAIL"
    assert medium["blockers"][0]["reachability"] == "production-reachable"
    assert dev_medium["status"] == "PASS"


def test_frontend_policy_requires_the_authoritative_web_root_and_rejects_mobile_substitution(tmp_path):
    policy = _load_policy()
    mobile = tmp_path / "mobile" / "package-lock.json"
    mobile.parent.mkdir()
    mobile.write_text(FRONTEND_LOCK.read_text(encoding="utf-8"), encoding="utf-8")

    with pytest.raises(policy.DependencyPolicyError, match="Web root"):
        policy.evaluate_frontend(
            audit=_frontend_audit(),
            lock_path=mobile,
            exceptions=_ledger(),
            now=NOW,
        )


def test_frontend_audit_node_and_installed_version_are_lock_bound():
    policy = _load_policy()
    audit = _frontend_audit(node="node_modules/not-in-root-lock")

    with pytest.raises(policy.DependencyPolicyError, match="root lock"):
        policy.evaluate_frontend(
            audit=audit,
            lock_path=FRONTEND_LOCK,
            exceptions=_ledger(),
            now=NOW,
        )


def test_exception_json_schema_is_closed_and_required_fields_match_runtime_validator():
    schema = json.loads(
        (ROOT / "schemas" / "release" / "dependency-exceptions-v1.schema.json").read_text(
            encoding="utf-8"
        )
    )
    item = schema["properties"]["exceptions"]["items"]

    assert schema["additionalProperties"] is False
    assert item["additionalProperties"] is False
    assert set(item["required"]) == {
        "ecosystem",
        "package",
        "advisory",
        "advisory_aliases",
        "installed_version",
        "lock_sha256",
        "dependency_scope",
        "severity",
        "reachability",
        "reachability_evidence",
        "owner",
        "approval_evidence",
        "expires_at",
        "target",
    }


def test_committed_ecdsa_exception_is_exact_approved_expiring_and_source_supported():
    policy = _load_policy()
    ledger = policy.load_json(ROOT / "evidence" / "phase-474" / "dependency-exceptions.json")
    validated = policy.validate_exception_ledger(ledger, now=NOW)

    assert validated == (
        {
            "ecosystem": "backend-python",
            "package": "ecdsa",
            "advisory": "PYSEC-2026-1325",
            "advisory_aliases": ["CVE-2024-23342", "GHSA-wj6h-64fc-37mp"],
            "installed_version": "0.19.2",
            "lock_sha256": "68efeb83c23ff4683cba1ff735130c365e8f9ec16dfb0eff5959a827536748fa",
            "dependency_scope": "runtime",
            "severity": "unavailable",
            "reachability": "proven-unreachable",
            "reachability_evidence": (
                "src/stoa/security/tokens.py enforces RS256 and algorithms RS256 only. "
                "src/stoa/security/jwks.py accepts RSA kty and constructs RSAKey only. "
                "Runtime code has no ecdsa signing keygen or ECDH invocation."
            ),
            "owner": "project-owner",
            "approval_evidence": (
                "Owner approved option 2 in Codex conversation on 2026-07-19 for exact "
                "30-day D-11 exception"
            ),
            "expires_at": "2026-08-18T09:00:00Z",
            "target": (
                "remove exception immediately when an upstream fixed release exists or replace "
                "python-jose/ecdsa through a separately reviewed auth-library/crypto-boundary "
                "change no later than expiry"
            ),
        },
    )

    tokens = (ROOT / "src" / "stoa" / "security" / "tokens.py").read_text(encoding="utf-8")
    jwks = (ROOT / "src" / "stoa" / "security" / "jwks.py").read_text(encoding="utf-8")
    runtime = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((ROOT / "src").rglob("*.py"))
    ).casefold()
    assert 'headers.get("alg") != "RS256"' in tokens
    assert 'algorithms=["RS256"]' in tokens
    assert 'raw_key.get("kty") != "RSA"' in jwks
    assert 'RSAKey(raw_key, algorithm="RS256")' in jwks
    assert "from ecdsa" not in runtime
    assert "import ecdsa" not in runtime
    assert "signingkey" not in runtime
    assert "sign_digest" not in runtime
    assert "ecdh" not in runtime


def test_backend_cli_defaults_to_the_committed_exception_ledger():
    policy = _load_policy()
    args = policy._parser().parse_args(["check-backend"])

    assert args.exceptions == ROOT / "evidence" / "phase-474" / "dependency-exceptions.json"


def test_committed_ecdsa_exception_accepts_only_the_exact_audit_identity():
    policy = _load_policy()
    lock = ROOT / "uv.lock"
    requirements = ROOT / "requirements.txt"
    runtime = policy._parse_runtime_requirements(requirements)
    audit = {
        "dependencies": [
            {
                "name": package,
                "version": version,
                "vulns": [
                    {
                        "id": "PYSEC-2026-1325",
                        "fix_versions": [],
                        "aliases": ["CVE-2024-23342", "GHSA-wj6h-64fc-37mp"],
                        "description": "not retained",
                    }
                ]
                if package == "ecdsa"
                else [],
            }
            for package, version in runtime.items()
        ],
        "fixes": [],
    }
    ledger = policy.load_json(ROOT / "evidence" / "phase-474" / "dependency-exceptions.json")

    accepted = policy.evaluate_backend(
        audit=audit,
        lock_path=lock,
        requirements_path=requirements,
        exceptions=ledger,
        now=NOW,
    )

    assert accepted["status"] == "PASS"
    assert accepted["blockers"] == []
    assert accepted["accepted_exceptions"] == [
        {
            "ecosystem": "backend-python",
            "package": "ecdsa",
            "advisory": "PYSEC-2026-1325",
            "advisory_aliases": ["CVE-2024-23342", "GHSA-wj6h-64fc-37mp"],
            "installed_version": "0.19.2",
            "lock_sha256": "68efeb83c23ff4683cba1ff735130c365e8f9ec16dfb0eff5959a827536748fa",
            "reachability": "proven-unreachable",
            "expires_at": "2026-08-18T09:00:00Z",
        }
    ]

    audit["dependencies"][next(
        index for index, item in enumerate(audit["dependencies"]) if item["name"] == "ecdsa"
    )]["vulns"][0]["aliases"] = ["CVE-2024-23342"]
    with pytest.raises(policy.DependencyPolicyError, match="unmatched"):
        policy.evaluate_backend(
            audit=audit,
            lock_path=lock,
            requirements_path=requirements,
            exceptions=ledger,
            now=NOW,
        )


def test_duplicate_json_fields_are_rejected(tmp_path):
    policy = _load_policy()
    path = tmp_path / "exceptions.json"
    path.write_text('{"schema":"one","schema":"two","exceptions":[]}', encoding="utf-8")

    with pytest.raises(policy.DependencyPolicyError, match="duplicate"):
        policy.load_json(path)


def test_supported_backend_advisory_fixes_are_present_in_frozen_runtime_lock():
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    versions = {
        item["name"]: item["version"]
        for item in lock["package"]
        if item["name"]
        in {"cryptography", "pydantic-settings", "python-multipart", "starlette"}
    }

    minimums = {
        "cryptography": "48.0.1",
        "pydantic-settings": "2.14.2",
        "python-multipart": "0.0.31",
        "starlette": "1.3.1",
    }
    assert set(versions) == set(minimums)
    assert all(Version(versions[name]) >= Version(minimum) for name, minimum in minimums.items())


def test_supported_backend_advisory_fixes_are_present_in_frozen_export():
    requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8")

    pins = dict(
        re.findall(
            r"^(cryptography|pydantic-settings|python-multipart|starlette)==([^ ]+) \\\\?$",
            requirements,
            re.MULTILINE,
        )
    )
    minimums = {
        "cryptography": "48.0.1",
        "pydantic-settings": "2.14.2",
        "python-multipart": "0.0.31",
        "starlette": "1.3.1",
    }
    assert set(pins) == set(minimums)
    assert all(Version(pins[name]) >= Version(minimum) for name, minimum in minimums.items())
