#!/usr/bin/env python3
"""Build and verify the shared AWS Lambda deployment package directory."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform as runtime_platform
import shutil
import stat
import subprocess
import sys
from typing import Any
import zipfile


MANIFEST_NAME = ".stoa-build-manifest.json"
RUNTIME_TARGET = "python3.12"
PYTHON_VERSION = "3.12"
PLATFORM = "manylinux2014_aarch64"
ARCHITECTURE = "arm64"
ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)
ZIP_FILE_MODE = 0o644
UV_HEADER = b"# This file was autogenerated by uv via the following command:\n"
UV_EXPORT_COMMANDS = {
    b"#    uv export --format requirements-txt --no-dev --no-emit-project --locked\n",
    b"#    uv export --format requirements-txt --no-dev --no-emit-project --locked "
    b"--output-file requirements.txt\n",
}
EXPECTED_HANDLERS = {
    "stoa.main.handler": "stoa/main.py",
    "stoa.jobs.weekly_reports.handler": "stoa/jobs/weekly_reports.py",
}
HASHED_SOURCE_ROOTS = ("src/stoa",)
HASHED_ROOT_FILES = ("requirements.txt", "pyproject.toml")
EXCLUDED_PARTS = {"__pycache__", ".pytest_cache", ".ruff_cache"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}
BUILD_MANIFEST_KEYS = {
    "schema_version",
    "project",
    "source_git_sha",
    "source_git_dirty",
    "source_tree_hash",
    "distribution_tree_hash",
    "requirements_hash",
    "pyproject_hash",
    "uv_lock_hash",
    "runtime_target",
    "python_version",
    "platform",
    "architecture",
    "expected_handlers",
    "handler_inventory",
    "boot_smoke",
    "cdk_asset_hash",
}


class DistVerificationError(RuntimeError):
    """Raised when a Lambda dist directory cannot be trusted."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _should_hash(path: Path) -> bool:
    return not (
        any(part in EXCLUDED_PARTS for part in path.parts)
        or path.suffix in EXCLUDED_SUFFIXES
        or path.name == ".DS_Store"
    )


def sha256_tree(root: Path, relative_roots: tuple[str, ...]) -> str:
    digest = hashlib.sha256()
    for relative_root in relative_roots:
        base = root / relative_root
        if not base.exists():
            raise DistVerificationError(f"Missing source path: {relative_root}")
        for path in sorted(p for p in base.rglob("*") if p.is_file() and _should_hash(p)):
            relative = path.relative_to(root).as_posix()
            digest.update(relative.encode("utf-8"))
            digest.update(b"\0")
            digest.update(sha256_file(path).encode("ascii"))
            digest.update(b"\0")
    return digest.hexdigest()


def sha256_dist_tree(dist_dir: Path) -> str:
    """Hash every distribution file except the manifest that records the hash."""
    digest = hashlib.sha256()
    for path in sorted(dist_dir.rglob("*")):
        if path.is_symlink():
            raise DistVerificationError("Lambda dist contains a symlink")
        if not path.is_file() or path.name == MANIFEST_NAME or not _should_hash(path):
            continue
        relative = path.relative_to(dist_dir).as_posix()
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(sha256_file(path).encode("ascii"))
        digest.update(b"\0")
    return digest.hexdigest()


def git_output(root: Path, *args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip()


def git_sha(root: Path) -> str:
    return git_output(root, "rev-parse", "HEAD") or "unknown"


def git_dirty(root: Path) -> bool:
    status = git_output(root, "status", "--porcelain")
    return bool(status)


def handler_inventory(dist_dir: Path) -> dict[str, dict[str, Any]]:
    inventory: dict[str, dict[str, Any]] = {}
    for handler, relative_file in EXPECTED_HANDLERS.items():
        path = dist_dir / relative_file
        module_attr = handler.rsplit(".", 1)[1]
        exists = path.exists()
        has_attr = False
        if exists:
            source = path.read_text(encoding="utf-8", errors="replace")
            has_attr = f"{module_attr} =" in source or f"def {module_attr}(" in source
        inventory[handler] = {
            "file": relative_file,
            "exists": exists,
            "has_attr": has_attr,
        }
    return inventory


def require_handlers(dist_dir: Path) -> dict[str, dict[str, Any]]:
    inventory = handler_inventory(dist_dir)
    for handler, status in inventory.items():
        if status["exists"] is not True or status["has_attr"] is not True:
            raise DistVerificationError(f"{handler}: missing or invalid handler")
    return inventory


def export_locked_requirements(repo_root: Path) -> bytes:
    """Export runtime requirements from the committed lock without mutation."""
    command = [
        "uv",
        "export",
        "--format",
        "requirements-txt",
        "--no-dev",
        "--no-emit-project",
        "--locked",
    ]
    try:
        result = subprocess.run(
            command,
            cwd=repo_root,
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise DistVerificationError("Fresh locked requirements export failed") from exc
    return result.stdout


def verify_locked_requirements(repo_root: Path) -> bytes:
    requirements_path = repo_root / "requirements.txt"
    lock_path = repo_root / "uv.lock"
    if not requirements_path.is_file() or not lock_path.is_file():
        raise DistVerificationError("requirements.txt or uv.lock is missing")
    exported = export_locked_requirements(repo_root)
    committed_header, committed_payload = _requirements_payload(requirements_path.read_bytes())
    exported_header, exported_payload = _requirements_payload(exported)
    if committed_header != exported_header or committed_payload != exported_payload:
        raise DistVerificationError("requirements.txt differs from the fresh locked export")
    return exported


def _requirements_payload(value: bytes) -> tuple[bool, bytes]:
    lines = value.splitlines(keepends=True)
    if len(lines) >= 2 and lines[0] == UV_HEADER and lines[1] in UV_EXPORT_COMMANDS:
        return True, b"".join(lines[2:])
    return False, value


def current_python_version() -> str:
    return runtime_platform.python_version()


def boot_smoke(dist_dir: Path) -> dict[str, Any]:
    """Import the exact handlers through an isolated Python 3.12 process."""
    if not current_python_version().startswith("3.12."):
        raise DistVerificationError("Lambda boot smoke requires Python 3.12")
    handler_pairs = [handler.rsplit(".", 1) for handler in sorted(EXPECTED_HANDLERS)]
    code = (
        "import importlib,json,sys;"
        "sys.path.insert(0,sys.argv[1]);"
        "pairs=json.loads(sys.argv[2]);"
        "assert all(callable(getattr(importlib.import_module(module), attr, None)) "
        "for module,attr in pairs)"
    )
    environment = dict(os.environ)
    for name in tuple(environment):
        if name.startswith("AWS_") or name in {
            "HTTP_PROXY",
            "HTTPS_PROXY",
            "ALL_PROXY",
            "http_proxy",
            "https_proxy",
            "all_proxy",
        }:
            environment.pop(name, None)
    environment["AWS_EC2_METADATA_DISABLED"] = "true"
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    try:
        subprocess.run(
            [sys.executable, "-I", "-c", code, str(dist_dir.resolve()), json.dumps(handler_pairs)],
            cwd=dist_dir,
            env=environment,
            check=True,
            capture_output=True,
            timeout=30,
        )
    except (OSError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        raise DistVerificationError("Lambda handler boot smoke failed") from exc
    return {
        "runtime_target": RUNTIME_TARGET,
        "handler_count": len(handler_pairs),
        "status": "PASS",
    }


def cdk_asset_hash(manifest: dict[str, Any]) -> str:
    stable_fields = {key: value for key, value in manifest.items() if key != "cdk_asset_hash"}
    encoded = json.dumps(stable_fields, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def build_manifest(
    repo_root: Path,
    dist_dir: Path,
) -> dict[str, Any]:
    requirements_path = repo_root / "requirements.txt"
    pyproject_path = repo_root / "pyproject.toml"
    uv_lock_path = repo_root / "uv.lock"
    if not requirements_path.exists():
        raise DistVerificationError("Missing requirements.txt")
    if not pyproject_path.exists():
        raise DistVerificationError("Missing pyproject.toml")
    verify_locked_requirements(repo_root)

    inventory = require_handlers(dist_dir)
    manifest = {
        "schema_version": 1,
        "project": "stoa-backend",
        "source_git_sha": git_sha(repo_root),
        "source_git_dirty": git_dirty(repo_root),
        "source_tree_hash": sha256_tree(repo_root, HASHED_SOURCE_ROOTS),
        "distribution_tree_hash": sha256_dist_tree(dist_dir),
        "requirements_hash": sha256_file(requirements_path),
        "pyproject_hash": sha256_file(pyproject_path),
        "uv_lock_hash": sha256_file(uv_lock_path),
        "runtime_target": RUNTIME_TARGET,
        "python_version": PYTHON_VERSION,
        "platform": PLATFORM,
        "architecture": ARCHITECTURE,
        "expected_handlers": sorted(EXPECTED_HANDLERS),
        "handler_inventory": inventory,
        "boot_smoke": boot_smoke(dist_dir),
    }
    manifest["cdk_asset_hash"] = cdk_asset_hash(manifest)
    return manifest


def validate_manifest(repo_root: Path, dist_dir: Path) -> dict[str, Any]:
    manifest_path = dist_dir / MANIFEST_NAME
    if not manifest_path.exists():
        raise DistVerificationError(f"Missing Lambda dist manifest: {manifest_path}")

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise DistVerificationError("Lambda dist manifest is malformed") from exc
    if not isinstance(manifest, dict):
        raise DistVerificationError("Lambda dist manifest is malformed")
    if set(manifest) != BUILD_MANIFEST_KEYS:
        raise DistVerificationError("Lambda dist manifest fields are not closed")
    expected_manifest = build_manifest(repo_root, dist_dir)
    expected = {
        key: value for key, value in expected_manifest.items() if key != "cdk_asset_hash"
    }
    errors: list[str] = []
    for key, expected_value in expected.items():
        actual_value = manifest.get(key)
        if actual_value != expected_value:
            errors.append(f"{key}: expected {expected_value!r}, found {actual_value!r}")

    inventory = manifest.get("handler_inventory") or {}
    current_inventory = handler_inventory(dist_dir)
    for handler, status in current_inventory.items():
        if not status["exists"]:
            errors.append(f"{handler}: missing dist file {status['file']}")
        if not status["has_attr"]:
            errors.append(f"{handler}: handler attribute missing in {status['file']}")
        recorded = inventory.get(handler) or {}
        if recorded.get("exists") is not True or recorded.get("has_attr") is not True:
            errors.append(f"{handler}: manifest does not record a valid handler")

    expected_asset_hash = cdk_asset_hash(manifest)
    if manifest.get("cdk_asset_hash") != expected_asset_hash:
        errors.append(
            "cdk_asset_hash: expected "
            f"{expected_asset_hash!r}, found {manifest.get('cdk_asset_hash')!r}"
        )

    if errors:
        joined = "\n  - ".join(errors)
        raise DistVerificationError(f"Lambda dist verification failed:\n  - {joined}")
    return manifest


def install_dependencies(repo_root: Path, dist_dir: Path) -> None:
    cmd = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--platform",
        PLATFORM,
        "--implementation",
        "cp",
        "--python-version",
        PYTHON_VERSION,
        "--only-binary",
        ":all:",
        "--target",
        str(dist_dir),
        "-r",
        str(repo_root / "requirements.txt"),
    ]
    subprocess.run(cmd, cwd=repo_root, check=True)


def copy_source(repo_root: Path, dist_dir: Path) -> None:
    source = repo_root / "src" / "stoa"
    destination = dist_dir / "stoa"
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo"))


def write_manifest(repo_root: Path, dist_dir: Path) -> dict[str, Any]:
    manifest = build_manifest(repo_root, dist_dir)
    manifest_path = dist_dir / MANIFEST_NAME
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def build_dist(repo_root: Path, dist_dir: Path, *, skip_install: bool = False) -> dict[str, Any]:
    verify_locked_requirements(repo_root)
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    dist_dir.mkdir(parents=True)
    if not skip_install:
        install_dependencies(repo_root, dist_dir)
    copy_source(repo_root, dist_dir)
    manifest = write_manifest(repo_root, dist_dir)
    validate_manifest(repo_root, dist_dir)
    return manifest


def zip_dist(dist_dir: Path, zip_path: Path) -> dict[str, Any]:
    if zip_path.exists():
        zip_path.unlink()
    paths: list[Path] = []
    for path in sorted(dist_dir.rglob("*")):
        if path.is_symlink():
            raise DistVerificationError("Lambda dist archive cannot contain a symlink")
        if path.is_file() and _should_hash(path):
            paths.append(path)
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in paths:
            relative = path.relative_to(dist_dir).as_posix()
            info = zipfile.ZipInfo(relative, date_time=ZIP_TIMESTAMP)
            info.create_system = 3
            info.external_attr = (stat.S_IFREG | ZIP_FILE_MODE) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(
                info,
                path.read_bytes(),
                compress_type=zipfile.ZIP_DEFLATED,
                compresslevel=9,
            )
    identity = {
        "bytes": zip_path.stat().st_size,
        "entry_count": len(paths),
        "sha256": sha256_file(zip_path),
    }
    validate_archive_identity(zip_path, identity)
    return identity


def validate_archive_identity(zip_path: Path, identity: dict[str, Any]) -> None:
    if set(identity) != {"bytes", "entry_count", "sha256"}:
        raise DistVerificationError("Lambda archive identity is not closed")
    if (
        not zip_path.is_file()
        or identity.get("bytes") != zip_path.stat().st_size
        or identity.get("sha256") != sha256_file(zip_path)
    ):
        raise DistVerificationError("Lambda archive digest or length mismatch")
    try:
        with zipfile.ZipFile(zip_path) as archive:
            infos = archive.infolist()
            if identity.get("entry_count") != len(infos):
                raise DistVerificationError("Lambda archive entry count mismatch")
            if [info.filename for info in infos] != sorted(info.filename for info in infos):
                raise DistVerificationError("Lambda archive order is not normalized")
            for info in infos:
                if (
                    info.date_time != ZIP_TIMESTAMP
                    or stat.S_IMODE(info.external_attr >> 16) != ZIP_FILE_MODE
                ):
                    raise DistVerificationError("Lambda archive metadata is not normalized")
            if archive.testzip() is not None:
                raise DistVerificationError("Lambda archive contains corrupt bytes")
    except (OSError, zipfile.BadZipFile) as exc:
        raise DistVerificationError("Lambda archive is malformed") from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--dist", type=Path, default=None)
    parser.add_argument("--verify-only", action="store_true")
    parser.add_argument("--skip-install", action="store_true")
    parser.add_argument("--zip", type=Path, default=None, help="Optional zip path to create after build")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    dist_dir = (args.dist or repo_root / "dist").resolve()
    try:
        if args.verify_only:
            manifest = validate_manifest(repo_root, dist_dir)
            print(
                "Lambda dist verified: "
                f"sha={manifest['source_git_sha']} "
                f"source_tree_hash={manifest['source_tree_hash'][:12]}"
            )
            return 0
        manifest = build_dist(repo_root, dist_dir, skip_install=args.skip_install)
        if args.zip:
            zip_dist(dist_dir, args.zip.resolve())
        print(
            "Lambda dist built: "
            f"sha={manifest['source_git_sha']} "
            f"source_tree_hash={manifest['source_tree_hash'][:12]}"
        )
        return 0
    except DistVerificationError as exc:
        print(str(exc), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
