#!/usr/bin/env python3
"""Evaluate backend and authoritative Web dependency audits without broad exceptions."""

from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
from hashlib import sha256
import json
from pathlib import Path
import re
import subprocess
import sys
import tomllib
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
FRONTEND_ROOT = Path("/Users/zhdeng/stoa-frontend")
FRONTEND_LOCK = FRONTEND_ROOT / "package-lock.json"
DEFAULT_EXCEPTIONS = ROOT / "evidence" / "phase-474" / "dependency-exceptions.json"
SCHEMA_VERSION = "stoa.release.dependency-exceptions.v1"
POLICY_RESULT_SCHEMA = "stoa.release.dependency-policy-result.v1"
POLICY_EXIT = 2
EXECUTION_EXIT = 3
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
PACKAGE_RE = re.compile(r"^[a-z0-9@][a-z0-9._@/-]*$")
ADVISORY_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{2,119}$")
VERSION_RE = re.compile(r"^[^*?<>~=,;\s]{1,80}$")
UTC_RE = re.compile(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$")
OWNER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._@-]{2,79}$")
EVIDENCE_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 ./_:#()-]{15,399}$")
TARGET_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 ._@:/()+-]{11,239}$", re.IGNORECASE)
REQUIREMENT_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\]+)(?:\s|\\|$)")
UV_HEADER = "# This file was autogenerated by uv via the following command:\n"
UV_EXPORT_HEADERS = {
    "#    uv export --format requirements-txt --no-dev --no-emit-project --locked\n",
    "#    uv export --format requirements-txt --no-dev --no-emit-project --locked "
    "--output-file requirements.txt\n",
}
EXCEPTION_KEYS = {
    "ecosystem",
    "package",
    "advisory",
    "advisory_aliases",
    "installed_version",
    "lock_sha256",
    "dependency_scope",
    "severity",
    "reachability",
    "reachability_evidence",
    "owner",
    "approval_evidence",
    "expires_at",
    "target",
}


class DependencyPolicyError(ValueError):
    """Stable, redacted rejection of dependency evidence or policy."""


def _canonical_json(value: object) -> str:
    return json.dumps(
        value,
        allow_nan=False,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    )


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    value: dict[str, Any] = {}
    for key, item in pairs:
        if key in value:
            raise DependencyPolicyError(f"duplicate JSON field: {key}")
        value[key] = item
    return value


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_reject_duplicate_keys)
    except DependencyPolicyError:
        raise
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise DependencyPolicyError("dependency JSON is unavailable or malformed") from exc
    if not isinstance(value, dict):
        raise DependencyPolicyError("dependency JSON must be an object")
    return value


def _normalize_package(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value.lower())


def _sha256_file(path: Path) -> str:
    try:
        return sha256(path.read_bytes()).hexdigest()
    except OSError as exc:
        raise DependencyPolicyError("dependency lock is unavailable") from exc


def _parse_utc(value: object, label: str) -> datetime:
    if not isinstance(value, str) or not UTC_RE.fullmatch(value):
        raise DependencyPolicyError(f"{label} is not an exact UTC timestamp")
    try:
        return datetime.strptime(value, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except ValueError as exc:
        raise DependencyPolicyError(f"{label} is not an exact UTC timestamp") from exc


def _require_string(value: object, pattern: re.Pattern[str], label: str) -> str:
    if not isinstance(value, str) or not pattern.fullmatch(value):
        raise DependencyPolicyError(f"{label} is malformed or broadened")
    if "*" in value or "?" in value:
        raise DependencyPolicyError(f"{label} contains a wildcard")
    return value


def validate_exception_ledger(
    ledger: Mapping[str, Any], *, now: datetime
) -> tuple[dict[str, Any], ...]:
    if set(ledger) != {"schema", "exceptions"} or ledger.get("schema") != SCHEMA_VERSION:
        raise DependencyPolicyError("dependency exception ledger fields or schema are invalid")
    values = ledger.get("exceptions")
    if not isinstance(values, list) or len(values) > 128:
        raise DependencyPolicyError("dependency exception inventory is malformed")
    if now.tzinfo is None or now.utcoffset() is None:
        raise DependencyPolicyError("policy clock must be timezone-aware")

    validated: list[dict[str, Any]] = []
    identities: set[tuple[str, str, str, str, str]] = set()
    for raw in values:
        if not isinstance(raw, dict) or set(raw) != EXCEPTION_KEYS:
            raise DependencyPolicyError("dependency exception fields are not closed")
        exception = dict(raw)
        if exception["ecosystem"] not in {"backend-python", "frontend-npm"}:
            raise DependencyPolicyError("dependency exception ecosystem is invalid")
        exception["package"] = _require_string(exception["package"], PACKAGE_RE, "package")
        exception["advisory"] = _require_string(exception["advisory"], ADVISORY_RE, "advisory")
        aliases = exception["advisory_aliases"]
        if (
            not isinstance(aliases, list)
            or len(aliases) > 16
            or any(
                not isinstance(alias, str) or not ADVISORY_RE.fullmatch(alias)
                for alias in aliases
            )
            or aliases != sorted(set(aliases))
            or exception["advisory"] in aliases
        ):
            raise DependencyPolicyError("advisory aliases are malformed or non-canonical")
        exception["installed_version"] = _require_string(
            exception["installed_version"], VERSION_RE, "installed version"
        )
        exception["lock_sha256"] = _require_string(
            exception["lock_sha256"], SHA256_RE, "lock SHA-256"
        )
        if exception["dependency_scope"] not in {
            "runtime",
            "web-root-production",
            "web-root-development",
        }:
            raise DependencyPolicyError("dependency scope is invalid")
        if exception["severity"] not in {"unavailable", "critical", "high", "moderate"}:
            raise DependencyPolicyError("dependency severity is invalid")
        if exception["reachability"] not in {"production-reachable", "proven-unreachable"}:
            raise DependencyPolicyError("dependency reachability is invalid")
        exception["reachability_evidence"] = _require_string(
            exception["reachability_evidence"], EVIDENCE_RE, "reachability evidence"
        )
        exception["owner"] = _require_string(exception["owner"], OWNER_RE, "exception owner")
        exception["approval_evidence"] = _require_string(
            exception["approval_evidence"], EVIDENCE_RE, "approval evidence"
        )
        expires_at = _parse_utc(exception["expires_at"], "exception expiry")
        if expires_at <= now.astimezone(timezone.utc):
            raise DependencyPolicyError("dependency exception is expired")
        exception["target"] = _require_string(exception["target"], TARGET_RE, "exception target")
        if not re.search(r"\b(?:upgrade|remove|replace)\b", exception["target"], re.IGNORECASE):
            raise DependencyPolicyError("exception target lacks an upgrade or removal action")

        identity = (
            exception["ecosystem"],
            _normalize_package(exception["package"]),
            exception["advisory"],
            exception["installed_version"],
            exception["lock_sha256"],
        )
        if identity in identities:
            raise DependencyPolicyError("duplicate dependency exception")
        identities.add(identity)
        validated.append(exception)
    return tuple(validated)


def _parse_runtime_requirements(path: Path) -> dict[str, str]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    except (OSError, UnicodeError) as exc:
        raise DependencyPolicyError("runtime requirements export is unavailable") from exc
    if len(lines) < 2 or lines[0] != UV_HEADER or lines[1] not in UV_EXPORT_HEADERS:
        raise DependencyPolicyError("runtime requirements export header is not authoritative")
    packages: dict[str, str] = {}
    for line in lines[2:]:
        match = REQUIREMENT_RE.match(line)
        if not match:
            continue
        package = _normalize_package(match.group(1))
        version = match.group(2)
        if package in packages or not VERSION_RE.fullmatch(version):
            raise DependencyPolicyError("runtime requirements export contains duplicate or broad pins")
        packages[package] = version
    if not packages:
        raise DependencyPolicyError("runtime requirements export is empty")
    return packages


def _validate_uv_lock(lock_path: Path, runtime: Mapping[str, str]) -> None:
    try:
        lock = tomllib.loads(lock_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as exc:
        raise DependencyPolicyError("uv lock is unavailable or malformed") from exc
    packages = lock.get("package")
    if not isinstance(packages, list):
        raise DependencyPolicyError("uv lock package inventory is malformed")
    locked: dict[str, set[str]] = {}
    for item in packages:
        if not isinstance(item, dict):
            raise DependencyPolicyError("uv lock package inventory is malformed")
        name = item.get("name")
        version = item.get("version")
        if isinstance(name, str) and isinstance(version, str):
            locked.setdefault(_normalize_package(name), set()).add(version)
    if any(version not in locked.get(name, set()) for name, version in runtime.items()):
        raise DependencyPolicyError("runtime requirements export is not bound to uv lock")


def _backend_blockers(
    audit: Mapping[str, Any], runtime: Mapping[str, str]
) -> list[dict[str, Any]]:
    if set(audit) != {"dependencies", "fixes"}:
        raise DependencyPolicyError("pip-audit fields are not closed")
    dependencies = audit.get("dependencies")
    if not isinstance(dependencies, list):
        raise DependencyPolicyError("pip-audit dependency inventory is malformed")
    observed: dict[str, str] = {}
    blockers: list[dict[str, Any]] = []
    for dependency in dependencies:
        if not isinstance(dependency, dict) or set(dependency) != {"name", "version", "vulns"}:
            raise DependencyPolicyError("pip-audit dependency fields are not closed")
        name = dependency.get("name")
        version = dependency.get("version")
        vulns = dependency.get("vulns")
        if not isinstance(name, str) or not isinstance(version, str) or not isinstance(vulns, list):
            raise DependencyPolicyError("pip-audit dependency identity is malformed")
        normalized = _normalize_package(name)
        if normalized in observed:
            raise DependencyPolicyError("pip-audit contains duplicate dependencies")
        observed[normalized] = version
        for vuln in vulns:
            if not isinstance(vuln, dict) or set(vuln) != {
                "id",
                "fix_versions",
                "aliases",
                "description",
            }:
                raise DependencyPolicyError("pip-audit advisory fields are not closed")
            advisory = _require_string(vuln.get("id"), ADVISORY_RE, "backend advisory")
            fix_versions = vuln.get("fix_versions")
            aliases = vuln.get("aliases")
            if not isinstance(fix_versions, list) or not all(
                isinstance(item, str) and VERSION_RE.fullmatch(item) for item in fix_versions
            ):
                raise DependencyPolicyError("backend advisory fixes are malformed")
            if not isinstance(aliases, list) or not all(
                isinstance(item, str) and ADVISORY_RE.fullmatch(item) for item in aliases
            ):
                raise DependencyPolicyError("backend advisory aliases are malformed")
            canonical_aliases = sorted(set(aliases))
            if advisory in canonical_aliases:
                raise DependencyPolicyError("backend advisory aliases repeat the primary advisory")
            blockers.append(
                {
                    "ecosystem": "backend-python",
                    "package": normalized,
                    "advisory": advisory,
                    "advisory_aliases": canonical_aliases,
                    "installed_version": version,
                    "dependency_scope": "runtime",
                    "severity": "unavailable",
                    "reachability": "production-reachable",
                    "fix_versions": sorted(set(fix_versions)),
                }
            )
    if observed != dict(runtime):
        raise DependencyPolicyError("pip-audit does not exactly cover the runtime export")
    return sorted(blockers, key=lambda item: (item["package"], item["advisory"]))


def _exception_identity(blocker: Mapping[str, Any], lock_sha256: str) -> tuple[Any, ...]:
    return (
        blocker["ecosystem"],
        blocker["package"],
        blocker["advisory"],
        tuple(blocker["advisory_aliases"]),
        blocker["installed_version"],
        lock_sha256,
        blocker["dependency_scope"],
        blocker["severity"],
    )


def _apply_exceptions(
    blockers: Sequence[dict[str, Any]],
    exceptions: Sequence[dict[str, Any]],
    *,
    lock_sha256: str,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    exception_map: dict[tuple[Any, ...], dict[str, Any]] = {}
    for exception in exceptions:
        identity = (
            exception["ecosystem"],
            _normalize_package(exception["package"]),
            exception["advisory"],
            tuple(exception["advisory_aliases"]),
            exception["installed_version"],
            exception["lock_sha256"],
            exception["dependency_scope"],
            exception["severity"],
        )
        exception_map[identity] = exception
    remaining: list[dict[str, Any]] = []
    accepted: list[dict[str, Any]] = []
    used: set[tuple[Any, ...]] = set()
    for blocker in blockers:
        identity = _exception_identity(blocker, lock_sha256)
        exception = exception_map.get(identity)
        if exception is None:
            remaining.append(blocker)
            continue
        used.add(identity)
        accepted.append(
            {
                "ecosystem": exception["ecosystem"],
                "package": _normalize_package(exception["package"]),
                "advisory": exception["advisory"],
                "advisory_aliases": exception["advisory_aliases"],
                "installed_version": exception["installed_version"],
                "lock_sha256": exception["lock_sha256"],
                "reachability": exception["reachability"],
                "expires_at": exception["expires_at"],
            }
        )
    if set(exception_map) != used:
        raise DependencyPolicyError("dependency exception is unmatched or stale")
    return remaining, accepted


def _result(
    *,
    ecosystem: str,
    lock_sha256: str,
    blockers: list[dict[str, Any]],
    accepted: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "schema": POLICY_RESULT_SCHEMA,
        "status": "PASS" if not blockers else "FAIL",
        "ecosystem": ecosystem,
        "lock_sha256": lock_sha256,
        "blockers": blockers,
        "accepted_exceptions": accepted,
    }


def evaluate_backend(
    *,
    audit: Mapping[str, Any],
    lock_path: Path,
    requirements_path: Path,
    exceptions: Mapping[str, Any],
    now: datetime,
) -> dict[str, Any]:
    runtime = _parse_runtime_requirements(requirements_path)
    _validate_uv_lock(lock_path, runtime)
    lock_sha256 = _sha256_file(lock_path)
    validated = validate_exception_ledger(exceptions, now=now)
    if any(item["ecosystem"] != "backend-python" for item in validated):
        raise DependencyPolicyError("backend evaluation received a foreign exception")
    blockers = _backend_blockers(audit, runtime)
    remaining, accepted = _apply_exceptions(blockers, validated, lock_sha256=lock_sha256)
    return _result(
        ecosystem="backend-python",
        lock_sha256=lock_sha256,
        blockers=remaining,
        accepted=accepted,
    )


def _frontend_lock_packages(lock_path: Path) -> dict[str, dict[str, Any]]:
    try:
        if lock_path.resolve(strict=True) != FRONTEND_LOCK.resolve(strict=True):
            raise DependencyPolicyError("frontend audit must use the authoritative Web root lock")
    except OSError as exc:
        raise DependencyPolicyError("authoritative Web root lock is unavailable") from exc
    lock = load_json(lock_path)
    if lock.get("lockfileVersion") != 3 or not isinstance(lock.get("packages"), dict):
        raise DependencyPolicyError("authoritative Web root lock is malformed")
    packages = lock["packages"]
    root = packages.get("")
    if lock.get("name") != "stoa-frontend" or not isinstance(root, dict):
        raise DependencyPolicyError("authoritative Web root lock identity is invalid")
    return packages


def _npm_advisory_id(via: Mapping[str, Any]) -> str:
    url = via.get("url")
    if isinstance(url, str):
        candidate = url.rstrip("/").rsplit("/", 1)[-1]
        if ADVISORY_RE.fullmatch(candidate):
            return candidate
    source = via.get("source")
    if isinstance(source, (str, int)) and ADVISORY_RE.fullmatch(str(source)):
        return str(source)
    raise DependencyPolicyError("npm advisory identity is malformed")


def _frontend_blockers(
    audit: Mapping[str, Any], packages: Mapping[str, Any]
) -> list[dict[str, Any]]:
    if set(audit) != {"auditReportVersion", "vulnerabilities", "metadata"}:
        raise DependencyPolicyError("npm audit fields are not closed")
    if audit.get("auditReportVersion") != 2 or not isinstance(audit.get("vulnerabilities"), dict):
        raise DependencyPolicyError("npm audit report is malformed")
    blockers: dict[tuple[str, str, str, str], dict[str, Any]] = {}
    for key, vulnerability in audit["vulnerabilities"].items():
        if not isinstance(key, str) or not isinstance(vulnerability, dict):
            raise DependencyPolicyError("npm vulnerability inventory is malformed")
        expected = {"name", "severity", "isDirect", "via", "effects", "range", "nodes", "fixAvailable"}
        if set(vulnerability) != expected or vulnerability.get("name") != key:
            raise DependencyPolicyError("npm vulnerability fields are not closed")
        severity = vulnerability.get("severity")
        nodes = vulnerability.get("nodes")
        via_items = vulnerability.get("via")
        if severity not in {"info", "low", "moderate", "high", "critical"}:
            raise DependencyPolicyError("npm vulnerability severity is unavailable")
        if not isinstance(nodes, list) or not nodes or not all(isinstance(node, str) for node in nodes):
            raise DependencyPolicyError("npm vulnerability nodes are malformed")
        if not isinstance(via_items, list) or not via_items:
            raise DependencyPolicyError("npm advisory inventory is missing")
        node_records: list[tuple[str, str, bool]] = []
        for node in nodes:
            record = packages.get(node)
            if not isinstance(record, dict) or not isinstance(record.get("version"), str):
                raise DependencyPolicyError("npm audit node is absent from the Web root lock")
            node_records.append((node, record["version"], record.get("dev") is not True))
        production = any(item[2] for item in node_records)
        if severity in {"info", "low"} or (severity == "moderate" and not production):
            continue
        for via in via_items:
            if isinstance(via, str):
                raise DependencyPolicyError("npm transitive advisory lacks an exact advisory record")
            if not isinstance(via, dict) or via.get("severity") != severity:
                raise DependencyPolicyError("npm advisory severity is inconsistent")
            advisory = _npm_advisory_id(via)
            for _, version, is_production in node_records:
                scope = "web-root-production" if is_production else "web-root-development"
                reachability = "production-reachable" if is_production else "proven-unreachable"
                blocker = {
                    "ecosystem": "frontend-npm",
                    "package": key,
                    "advisory": advisory,
                    "advisory_aliases": [],
                    "installed_version": version,
                    "dependency_scope": scope,
                    "severity": severity,
                    "reachability": reachability,
                    "fix_versions": [],
                }
                blockers[(key, advisory, version, scope)] = blocker
    return [blockers[key] for key in sorted(blockers)]


def evaluate_frontend(
    *,
    audit: Mapping[str, Any],
    lock_path: Path,
    exceptions: Mapping[str, Any],
    now: datetime,
) -> dict[str, Any]:
    packages = _frontend_lock_packages(lock_path)
    lock_sha256 = _sha256_file(lock_path)
    validated = validate_exception_ledger(exceptions, now=now)
    if any(item["ecosystem"] != "frontend-npm" for item in validated):
        raise DependencyPolicyError("frontend evaluation received a foreign exception")
    blockers = _frontend_blockers(audit, packages)
    remaining, accepted = _apply_exceptions(blockers, validated, lock_sha256=lock_sha256)
    return _result(
        ecosystem="frontend-npm",
        lock_sha256=lock_sha256,
        blockers=remaining,
        accepted=accepted,
    )


def _empty_ledger() -> dict[str, Any]:
    return {"schema": SCHEMA_VERSION, "exceptions": []}


def _policy_now(value: str | None) -> datetime:
    if value is None:
        return datetime.now(timezone.utc)
    return _parse_utc(value, "policy clock")


def _run_pip_audit(requirements: Path) -> dict[str, Any]:
    executable = Path(sys.executable).with_name("pip-audit")
    command = (
        str(executable),
        "--require-hashes",
        "--disable-pip",
        "--no-deps",
        "--requirement",
        str(requirements),
        "--format",
        "json",
        "--progress-spinner",
        "off",
    )
    try:
        result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, timeout=300)
    except (OSError, subprocess.SubprocessError) as exc:
        raise DependencyPolicyError("pip-audit execution failed") from exc
    if result.returncode not in {0, 1}:
        raise DependencyPolicyError("pip-audit did not produce a policy result")
    try:
        value = json.loads(result.stdout, object_pairs_hook=_reject_duplicate_keys)
    except (json.JSONDecodeError, DependencyPolicyError) as exc:
        raise DependencyPolicyError("pip-audit machine result is malformed") from exc
    if not isinstance(value, dict):
        raise DependencyPolicyError("pip-audit machine result is malformed")
    return value


def _write_result(value: Mapping[str, Any]) -> None:
    sys.stdout.write(json.dumps(value, indent=2, sort_keys=True) + "\n")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    backend = subparsers.add_parser("check-backend")
    backend.add_argument("--lock", type=Path, default=ROOT / "uv.lock")
    backend.add_argument("--requirements", type=Path, default=ROOT / "requirements.txt")
    backend.add_argument("--audit", type=Path)
    backend.add_argument("--exceptions", type=Path, default=DEFAULT_EXCEPTIONS)
    backend.add_argument("--now")
    frontend = subparsers.add_parser("check-frontend")
    frontend.add_argument("--lock", type=Path, default=FRONTEND_LOCK)
    frontend.add_argument("--audit", type=Path, required=True)
    frontend.add_argument("--exceptions", type=Path)
    frontend.add_argument("--now")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        exceptions = load_json(args.exceptions) if args.exceptions else _empty_ledger()
        if args.command == "check-backend":
            audit = load_json(args.audit) if args.audit else _run_pip_audit(args.requirements)
            result = evaluate_backend(
                audit=audit,
                lock_path=args.lock,
                requirements_path=args.requirements,
                exceptions=exceptions,
                now=_policy_now(args.now),
            )
        else:
            result = evaluate_frontend(
                audit=load_json(args.audit),
                lock_path=args.lock,
                exceptions=exceptions,
                now=_policy_now(args.now),
            )
    except DependencyPolicyError as exc:
        _write_result(
            {
                "schema": POLICY_RESULT_SCHEMA,
                "status": "FAIL",
                "error": str(exc),
                "production_operations": "NOT RUN",
            }
        )
        return POLICY_EXIT
    _write_result(result)
    return 0 if result["status"] == "PASS" else POLICY_EXIT


if __name__ == "__main__":
    raise SystemExit(main())
